### ISSUE TITLE
Question: Connection passwords must not be saved as a plain text - safer solution needs to be agreed and applied.

### ISSUE THREAD

**Issue by zruzicka** [zruzicka/db-browser-controller#11]
**Problem**: Connection passwords must not be saved as a plain text.

**Solution proposal**:
* Would you agree with applying password symmetric encryption and decryption?
  * In DB would be persisted password encrypted value. Password would be decrypted before applying credentials into new DB connection.

**Comment by LukasKolekAtaccama** [comment]
This is fine. Plus I have a hint: is it enough to only hash a password characters and store it to db?

**Comment by zruzicka** [comment]
Thank you @LukasKolekAtaccama for all provided responses (also in other tickets).

> This is fine. Plus I have a hint: is it enough to only hash a password characters and store it to db?

Password hash or in general asymmetric encryption works well when we need to check a match with other String. But I do not see a simple solution how to use password hash when we need to provide original password value to some other service (like when we want to open JDBC connection).

Or do you @LukasKolekAtaccama see some other efficient solution of using password hash and still being able to open JDBC connection?

**Comment by LukasKolekAtaccama** [comment]
I'm ok with the process in this case. The hint was pointing to something else, but it doesn't matter now, because it can be easily added later, maybe your solution will contain that anyway (I just don't want to say the name of that small improvement, because then it's simple :) ).

**Comment by zruzicka** [comment]
* There has been added Connection password encryption/decryption so there is persisted only encrypted password value.
* For each Connection record there is generated random salt further applied during SecretKey derivation (so each persisted encrypted-password value is different also for the same passwords).
* Connection specific SecretKey is derived as a part of each encryption/decryption request.
* These extensions added with `Issue-11`/`issue-11` commits message prefix.

If you @LukasKolekAtaccama would agree with this solution, we can close this issue ticket. (Sorry for delivering these extensions without a proper pull-request, but current encryption/decryption is still better than original plain text version. ;))
Or what is that small improvement which you have in your mind? Does it have something to do with a salt? :)

**Comment by LukasKolekAtaccama** [comment]
Yes I was talking about salt 👍

**Comment by zruzicka** [comment]
Ok, thank you @LukasKolekAtaccama. So this ticket can be considered as resolved.
