### ISSUE TITLE
Question: Mandatory DB Connection fields

### ISSUE THREAD

**Issue by zruzicka** [zruzicka/db-browser-controller#12]
**Problem**: 
* At the moment all `cz.zr.browser.dto.request.ConnectionRequestDto` fields are defined as mandatory, but this may not be optimal for real use cases.
  * For example `databaseName` and `password` could be an Optional fields?

**Question**:
* Is there any strict requirements which fields are mandatory and which can be Optional or does it depends mainly on our own preference?

**Solution proposal**:
* Until there will be any further requirements based on real use cases, `ConnectionRequestDto` fields can be further processed as mandatory for simplicity.

**Comment by LukasKolekAtaccama** [comment]
For this task there are no strict requirements for api.

(Out of scope for the task) Btw users usually want to specify JDBC connection string instead of host+port+database. There are more possible parameters in the connection string, so this improvement would make the api more generic.

**Comment by zruzicka** [comment]
Thanks @LukasKolekAtaccama for suggested new use case. So the following solution proposal https://github.com/zruzicka/db-browser-controller/issues/15 was created into backlog and this question ticket will be closed.
