### ISSUE TITLE
Question: Clarification of Table Statistics - "number of attributes"

### ISSUE THREAD

**Issue by zruzicka** [zruzicka/db-browser-controller#7]
Bonus tasks description defines:

> Single endpoint for statistics about each table: number of records, number of attributes.

**Question**: What is meant by "number of attributes"?

**Solution proposal**:
* Would it be enough to provide total Columns count for selected table?
* Columns count can be implemented for example via following SQL query:
```
SELECT COUNT(*) AS `columns`
FROM `information_schema`.`columns`
WHERE `table_schema` = {selected_schema} 
  AND `table_name` =  {selected_table};
```
---
**Current state**:
FYI Currently there is implemented just `recordsCount` as a part of Table Statistics.

**Comment by LukasKolekAtaccama** [comment]
Yes, in our language we use the term "attribute" for table column.

**Comment by zruzicka** [comment]
Thanks Lukas for clarification.
Delivered following:
* `columnsCount` field just included into Table statistics. 
* PathVariable schemaName included into table statistics endpoint and into columnsCount query.
* (Commits with issue-7 message prefix.)

This issue is resolved.
